language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: datarimasdevops
  api_key:
    secure: qXUFrhvI0WsAhdWR3kGcU0zkigsqpiq8uf0n8r1fm2XYshMrkwS4RxXXsMSJ7knAvAQZDFEB7c7cncKevOD19J3pheA86J6iDiZsEUyTbWL4Gq5FXkhCA8u07euoOeSjvE5TrfArhoaWtCa/ne2PAISRXq+xURLobAcxJlEbDc70Vyi3nHF5A90jwcE1Q/a/V3j4f5dkdGPxRpoY60r9oTImISyf7rrzMqlZHkm+JE5HaGmnQXYT9SSp7UpfuFFOmcNrROVE4XugDMkbuWagpzcG9SMZjyl2CS8hSrpAF8P5LR9WGEGUszVYg9t4bXvrcKhW4tJMZ+BJ35ydJu7dgVvAfvRNCegcXeuC6g/bnZWCTJSLK5wdB6sjinhkOUV8l5PG5gMe/AFma0M8CjT0qmBosNdIfrCY74Ld1CrXBQEjiMgVtHHumJOVliCOjdqyCVgCKda2HaSm6QiakWfFoBowpSUuIwORyn8jdRoqfxBL15gDWRmzv71/ocMyF9nPtC8C+nBjeYuxDKojlizhKooSbClZBRMQsznQwivKBxl8FRYWk0Jj+pLQW98HypeJ749dhLKVmaT+HGdJCK5yV15DstDFvYNjoUyi9lqS92LQzvkVRKfYTBA1s8PVt2FF5tzdCV5rIaMnJsC+M9oiSmvFujAmJDwCgu/ujEmYQgI=
